### ISSUE TITLE
Your model can process the multi-edits?

### ISSUE THREAD

**Issue by hhhhzzzzz** [molecule-one/megan#6]
Hi, 
    Could you tell me whether your method can process the multi-edits?

Thanks!

**Comment by hhhhzzzzz** [comment]
The multi-edits mean multi bonds deleting and adding leaving groups

**Comment by mikolajsacha** [comment]
Hi,
If you mean our model proposing multiple edits at a time, then the answer is no - the model proposes edits sequentially, one at a time.
If you mean our model proposing multiple edits of bonds sequentially, then yes - for example, the model can propose deleting some bond and then deleting some other bond. Similarly, the model can generate one new atom with a bond in a single step, so it can generate any leaving group, but it can take several steps.

Best,
Mikołaj

**Comment by hhhhzzzzz** [comment]
OK, Thank you so much!
